### ISSUE TITLE
no such element {"method" : "class name", "selector" : "give_me"}

### ISSUE THREAD

**Issue by egg-west** [LingDong-/wechit#2]
This Error is probably sensitive to the version of chrome or the platform.

Happened when I scanned the QR and press a key.
```
press a key after scanning...1
Traceback (most recent call last):
  File "wechit.py", line 500, in <module>
    main()
  File "wechit.py", line 453, in main
    print("logged in as \""+get_username(driver)+"\"! loading chats...")
  File "wechit.py", line 299, in get_username
    driver.find_element_by_class_name("give_me").find_element_by_class_name("display_name").get_attribute("innerHTML")
  File "/root/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/root/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/root/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"give_me"}
  (Session info: headless chrome=70.0.3538.110)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 3.10.0-693.2.2.el7.x86_64 x86_64)
```

**Comment by LingDong-** [comment]
Hi,

From this error, and your last error in the other issue, it seems that you've not logged in successfully. The two errors both indicates that the WeChat web interface did not load at all.

Did you scan the QR code with your phone when it appeared in the Terminal?

After you scan the QR code with WeChat on your phone, you would see something like the screenshot below, and you need to tap "Log In". After that, wechit will load your chats automatically (or after you press ENTER, in case you're using the patch code I gave you in the other issue).

![img_9944](https://user-images.githubusercontent.com/7929704/49530522-647cb280-f886-11e8-9d15-6ac8cce89ffb.PNG)

**Comment by zhaoxuyan** [comment]
python 2.7.15
mac
chrome : 版本 79.0.3945.88（正式版本） （64 位）
Happened when I scanned the QR and press a key.
```
press a key after scanning...
Traceback (most recent call last):
  File "wechit.py", line 495, in <module>
    main()
  File "wechit.py", line 448, in main
    print("logged in as \""+get_username(driver)+"\"! loading chats...")
  File "wechit.py", line 294, in get_username
    driver.find_element_by_class_name("give_me").find_element_by_class_name("display_name").get_attribute("innerHTML")
  File "/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/zhaoxuyan/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".give_me"}
  (Session info: headless chrome=79.0.3945.88)
```

**Comment by ChenDanCMU** [comment]
Same issue here. 
OS: Debian 10 buster
chrome: 79
python: 3.77
Traceback (most recent call last):
  File "wechit.py", line 488, in <module>
    main()
  File "wechit.py", line 441, in main
    print("logged in as \""+get_username(driver)+"\"! loading chats...")
  File "wechit.py", line 287, in get_username
    driver.find_element_by_class_name("give_me").find_element_by_class_name("display_name").get_attribute("innerHTML")
  File "/home/chen/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/home/chen/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/chen/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/chen/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".give_me"}
  (Session info: headless chrome=79.0.3945.130)
